# Generated by Django 2.2.1 on 2020-07-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200627_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='images/abana')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateTimeField()),
                ('fathers_name', models.CharField(max_length=100)),
                ('mothers_name', models.CharField(max_length=100)),
                ('umurenge', models.CharField(max_length=50)),
                ('akagali', models.CharField(max_length=50)),
                ('umudugudu', models.CharField(max_length=50)),
                ('igihe_yabyariye', models.DateField()),
                ('abana_afite', models.IntegerField(default=1)),
                ('ikiciro_ubudehe', models.CharField(max_length=1)),
                ('afite_ubwishingizi', models.BooleanField(default=False)),
                ('testimonials', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AbitejeImbere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='images/abana')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateTimeField()),
                ('umurenge', models.CharField(max_length=50)),
                ('akagali', models.CharField(max_length=50)),
                ('umudugudu', models.CharField(max_length=50)),
                ('testimonials', models.CharField(max_length=250)),
                ('categories', models.ManyToManyField(related_name='Abana', to='app.WorkCategory')),
            ],
        ),
    ]
