# Generated by Django 2.2.1 on 2020-07-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_abana_abitejeimbere_workcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abana',
            name='testimonials',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='abitejeimbere',
            name='testimonials',
            field=models.TextField(),
        ),
    ]
