# Generated by Django 2.2.1 on 2020-07-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200702_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abitejeimbere',
            name='categories',
            field=models.ManyToManyField(related_name='abana', to='app.WorkCategory'),
        ),
    ]
