# Generated by Django 2.2.1 on 2020-07-03 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200702_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='website',
            field=models.URLField(default=django.utils.timezone.now, max_length=2083),
            preserve_default=False,
        ),
    ]
