# Generated by Django 2.2.1 on 2020-08-10 13:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_blogpost_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/event'),
            preserve_default=False,
        ),
    ]
