# Generated by Django 2.2.1 on 2020-08-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_event_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='images/abana')),
                ('full_name', models.CharField(max_length=100)),
                ('umurenge', models.CharField(max_length=50)),
                ('akagali', models.CharField(max_length=50)),
                ('umudugudu', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('categories', models.ManyToManyField(related_name='abana', to='app.WorkCategory')),
            ],
        ),
        migrations.DeleteModel(
            name='AbitejeImbere',
        ),
    ]
