# Generated by Django 2.2.1 on 2020-08-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200816_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='categories',
            field=models.ManyToManyField(related_name='program', to='app.WorkCategory'),
        ),
    ]
