# Generated by Django 2.2.1 on 2020-08-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20200816_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
